--> DEFINE LOCATIONS OF PLUGIN CONFIGS
require 'lsp.lsp_config'
require 'lsp.mason-lsp-config'
require 'lsp.neodev'

require 'plugins.autopairs'
require 'plugins.cmp'
require 'plugins.colorizer'
require 'plugins.comments'
require 'plugins.dap'
require 'plugins.gitsigns'
require 'plugins.project'
require 'plugins.telescope'
require 'plugins.tex'
require 'plugins.toggleterm'
require 'plugins.treesitter'
require 'plugins.which-key'
require 'plugins.todo'

require 'ui.bufferline'
require 'ui.staline'
require 'ui.nvim-tree'
require 'ui.starter'