--> DEFINE LOCATIONS OF PLUGIN CONFIGS
require 'lsp.lsp_config'
require 'lsp.mason'
require 'lsp.null_ls'
require 'lsp.neodev'

require 'plugins.autopairs'
require 'plugins.cmp'
require 'plugins.colorizer'
require 'plugins.comments'
require 'plugins.dap'
require 'plugins.gitsigns'
require 'plugins.project'
require 'plugins.telescope'
require 'plugins.tex'
require 'plugins.toggleterm'
require 'plugins.treesitter'
require 'plugins.whichkey'
require 'plugins.todo'

require 'ui.bufferline'
require 'ui.staline'
require 'ui.nvim-tree'
require 'ui.starter'