--> DEFINE LOCATIONS OF PLUGIN CONFIGS
require 'plugins.lsp.lsp_config'
require 'plugins.lsp.mason'
require 'plugins.lsp.null_ls'
require 'plugins.lsp.neodev'

require 'plugins.dap.dap'

require 'plugins.autopairs'
require 'plugins.cmp'
require 'plugins.colorizer'
require 'plugins.comments'
require 'plugins.gitsigns'
require 'plugins.project'
require 'plugins.telescope'
require 'plugins.tex'
require 'plugins.toggleterm'
require 'plugins.treesitter'
require 'plugins.whichkey'
require 'plugins.todo'

require 'plugins.ui.bufferline'
require 'plugins.ui.staline'
require 'plugins.ui.nvim-tree'
require 'plugins.ui.starter'